import LocalizedStrings from "localized-strings";

export const cvTemplateLocalization = new LocalizedStrings({
  en: {
    name: "Name",
    surname: "Surname",
    photo: "Photo",
    goals: "Goals",
    skillsAndTechnologies: "Skills and technologies",
    experience: "Experience",
    links: "Links",
    foreignLanguages: "Foreign languages knowledge",
    workingExperience: "Working experience",
    otherExperience: "Other experience",
    education: "Education",
    specialty: "Specialty",
    degree: "Degree",
    jobType: {
      dev: "Developer",
      qa: "QA",
      economics: "Economics",
      marketing: "Marketing",
      sales: "Sales",
      customerService: "Customer Service",
      design: "Design",
    },
  },
  ua: {
    name: "Ім'я",
    surname: "Прізвище",
    photo: "Фото",
    goals: "Цілі",
    skillsAndTechnologies: "Навички та технології",
    experience: "Досвід",
    links: "Посилання",
    foreignLanguages: "Знання іноземних мов",
    workingExperience: "Досвід роботи",
    otherExperience: "Інший досвід",
    education: "Освіта",
    specialty: "Спеціальність",
    degree: "Науковий ступінь",
    jobType: {
      dev: "Розробник",
      qa: "QA",
      economics: "Економіка",
      marketing: "Маркетинг",
      sales: "Продажі",
      customerService: "Підтримка клієнтів",
      design: "Дизайн",
    },
  },
});
