const theme = {
  ltr: "text-left",
  rtl: "text-right",
  placeholder: "",
  paragraph: "relative mb-2 m-0 last:mb-0",
  quote:
    "text-base text-gray-500 ml-5 m-0 pl-4 border-l-gray-500 border-solid border-l-4",
  heading: {
    h1: "text-2xl mb-3 m-0 p-0",
    h2: "text-lg mt-2.5 m-0 p-0",
    h3: "text-lg mt-2.5 m-0 p-0",
    h4: "text-lg mt-2.5 m-0 p-0",
    h5: "text-lg mt-2.5 m-0 p-0",
  },
  list: {
    nested: {
      listitem: "list-none",
    },
    ol: "ml-4 m-0 p-0 list-decimal",
    ul: "ml-4 m-0 p-0 list-disc",
    listitem: "mx-8 my-2",
  },
  image: "editor-image",
  link: "editor-link",
  text: {
    bold: "font-bold",
    italic: "italic",
    overflowed: "editor-text-overflowed",
    hashtag: "editor-text-hashtag",
    underline: "underline",
    strikethrough: "line-through",
    underlineStrikethrough: "underline line-through",
    code: "bg-gray-100 text-[94%] px-1 py-px font-mono",
  },
  code: "font-mono bg-gray-100 block leading-relaxed text-sm whitespace-pre overflow-x-auto relative my-2 m-0 pl-14 pr-2 py-2",
  codeHighlight: {
    atrule: "editor-tokenAttr",
    attr: "editor-tokenAttr",
    boolean: "editor-tokenProperty",
    builtin: "editor-tokenSelector",
    cdata: "editor-tokenComment",
    char: "editor-tokenSelector",
    class: "editor-tokenFunction",
    "class-name": "editor-tokenFunction",
    comment: "editor-tokenComment",
    constant: "editor-tokenProperty",
    deleted: "editor-tokenProperty",
    doctype: "editor-tokenComment",
    entity: "editor-tokenOperator",
    function: "editor-tokenFunction",
    important: "editor-tokenVariable",
    inserted: "editor-tokenSelector",
    keyword: "editor-tokenAttr",
    namespace: "editor-tokenVariable",
    number: "editor-tokenProperty",
    operator: "editor-tokenOperator",
    prolog: "editor-tokenComment",
    property: "editor-tokenProperty",
    punctuation: "editor-tokenPunctuation",
    regex: "editor-tokenVariable",
    selector: "editor-tokenSelector",
    string: "editor-tokenSelector",
    symbol: "editor-tokenProperty",
    tag: "editor-tokenProperty",
    url: "editor-tokenOperator",
    variable: "editor-tokenVariable",
  },
};

export default theme;
